spring:
  config:
    import:
      - prod/amadeus.yml
      - prod/datasource.yml
      - prod/tour.yml
      - prod/weather.yml
      - prod/gcs.yml
  jackson:
#    default-property-inclusion: non_null

temp-string: prod